name = "cfapi"  # worker instance name
main = "app/index.ts" # app entry
minify = true
compatibility_date = "2025-02-14"
[[d1_databases]]
# expose in your worker on  env.DB
# our D1 database is now accessible via the DB binding
binding = "CFDB"
database_name = "cfd1"
database_id = "22a2e03b-f982-48ae-8c76-d74839a29803"
migrations_dir = "drizzle/migrations"
[assets]
directory = "public"
binding = "ASSETS"
# serve index.html for all unmatched routes
not_found_handling = "single-page-application"
[vars]
PULLING_DATABASE = "https://dog.ceo/api/breeds/image/random"

